### ISSUE TITLE
Entity constructor not currently relevant

### ISSUE THREAD

**Issue by eugene-davis** [IndustrialDragonfly/DEdC#63]
Currently all the entity constructor does is rather pointless, as the client will always - or nearly always be passing us details of what it is creating when it creates it - i.e. we will have an associative array to load. The case of no associative array should still be supported, though at the moment the controller does not support that.

This means that the Entity constructor needs to know what the calling parameters were. Some of the things relevant to this are already marked in TODOs, but there may be more.

**Comment by eugene-davis** [comment]
I suspect there should be questions.

**Comment by JoshuaJClark** [comment]
isnt that the point of the loadAssociativeArray function?
i.e. couldnt the controller just call:
$newthingy =  new Process($storage, $parentId);
$newthingy->loadAssociativeArray($someAssociativeArray);
this would accomplish the same thing with less redundant code (otherwise im basically duplicating loadAssociativeArray in the constructor

**Comment by JoshuaJClark** [comment]
should loadAssociativeArray have access to setting id? by design access to id is very locked down, this basically creates a set id function

**Comment by JoshuaJClark** [comment]
also currently the whole associative array is being passed down the constructor tree,  in the parent class many of the things in the array will not be accessable, so this would need to be called at the end points to work

**Comment by JoshuaJClark** [comment]
done but needs testing,
